import type { NextPage } from 'next'
import footer from '../common/footer'
import Head from "next/head";
import Image from 'next/image'
import logo from '../public/img/logo.png'
import Footer from '../common/footer'
import Link from 'next/link';
import Menu from '../common/menu';
import React, { useState } from 'react';
import Modal from '../commponent/Modal';
import Btn from '../common/btn';
import { useRouter } from 'next/router'


const Dashbord: NextPage = () => {
    const router = useRouter()

    const [open, setOpen] = useState(1);

    const handleClick = () => {
        if (open == 1) {
            setOpen(0)
        } else {
            setOpen(1);
        }
    }
    const setfun = () => {
    
    }
    const linkset = () => {
        router.push("/kyc")
    }
    return (
        <div className='bg-amir dark:bg-[#16142E]'>
            <div className='container h-auto mx-auto'>
                <Head>
                    <title>   User Dashbored </title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className=' w-full lg:flex h-auto col-span-2 bg-[#D3D3D3] dark:bg-[#16142E]'>
                    <div className='w-[15%] hidden lg:block   h-auto '>
                        <div className='md:h-[126px] xl:h-[80px] w-[100%]   lg:block md:pl-[33px] xl:pl-[16px]  dark:text-[#7AFDD6] dark:bg-[#211F41] xl:pt-[16px] md:pt-[40px] font-[900] md:text-[35px] xl:text-[16px] border-b-[1px] bg-[#F0EEFF] border-r-[1px] border-[#e4e2eff5] '>
                            Vivastarter
                        </div>
                        <Menu />


                    </div>
                    <div className='w-[93%] h-auto '>

                        <div className='md:h-[126px] xl:h-[80px]  text-right w-full flex  dark:bg-[#211F41] bg-[#F0EEFF] border-b-[1px] border-gray-600'>
                            <div className='w-[68%]'>
                                <div className='w-[201px] md:h-[126px] xl:h-[80px] border-r-[0.5px] border-[#9b9999] text-left flex md:pt-[53px] xl:pt-[26px] pl-[20px] md:text-[20px] xl:text-[17px]' >
                                    connected     <img src='./img/leak.svg' className='md:w-[48px] xl:w-[38px] md:h-[48px] xl:h-[38px] mt-[-10px] ml-[10px]' />
                                </div>
                            </div>
                            
                            

                        </div>

                        <div className='grid grid-cols-2 w-[93%] mt-[30px] mx-auto h-auto text-center pt-8px'>
                            <div className='w-[95%] h-auto grid  '>
                                <div className='w-[100%] h-[70px]  rounded-[20px] bg-gradient-to-r text-right from-[#36344A] border-r-0 to-[#181726] border-[4px] border-[#3B28CC]'>
                                    <div className='float-left  ml-[14px] mt-[15px] text-[20px] font-[500]'>Viva Token</div>
                                    <div className='w-[70px]  float-right h-[70px] rounded-[20px] border-[4px] border-[#36344A]  mt-[-4px] bg-[#3B28CC]'>
                                        <p className=' text-center mt-[15px] text-[20px] font-[700]'>buy</p>
                                    </div>
                                </div>
                                <div className='w-[100%] h-[70px] mt-[72px] rounded-[20px] bg-gradient-to-r text-right from-[#36344A] border-r-0 to-[#181726] border-[4px] border-[#3B28CC]'>
                                    <div className='float-left  ml-[14px] mt-[15px] text-[20px] font-[500]'>Tier: 2</div>
                                    <div className='w-[70px]  float-right h-[70px] rounded-[20px] border-[4px] border-[#36344A]  mt-[-4px] bg-[#3B28CC]'>
                                        <p className=' text-center mt-[15px] text-[20px] font-[700]'>calc</p>
                                    </div>
                                </div>
                                <div className='w-[100%] h-[70px]  rounded-[20px] mt-[72px] bg-gradient-to-r text-right from-[#36344A] border-r-0 to-[#181726] border-[4px] border-[#3B28CC]'>
                                    <div className='float-left  ml-[14px] mt-[15px] text-[20px] font-[500]'>Staked: 10</div>
                                    <div className='w-[70px]  float-right h-[70px] rounded-[20px] border-[4px] border-[#36344A]  mt-[-4px] bg-[#3B28CC]'>
                                        <p className=' text-center mt-[15px] text-[20px] font-[700]'>calc</p>
                                    </div>
                                </div>
                                <div className='w-[100%] h-[500px] bg-gradient-to-br from-[#3E3394] to-[#262436] mt-[49px] pt-[2px] pl-[2px] rounded-[20px]'>
                                    <div className='w-[99.8%] h-[494px]  rounded-[20px] pt-[15px] bg-gradient-to-br from-[#282452] to-[#323046]'>
                                        <div className='border-b-[3px] border-[#3B28CC] w-full  h-[90px] text-left pl-[24px] pt-[15px] font-[700] text-[20px]'>
                                            Lottery Probabilities
                                        </div>
                                        <div className='border-b-[3px] border-[#3B28CC] w-full  h-[60px] text-left pl-[24px] pt-[15px] font-[700] text-[30px] flex'>
                                            <p className='text-[16px] font-[700]'>250+ VIV</p>
                                            <p className='pl-[270px] text-[16px] font-[700] text-[#7AFDD6]'>5.21%</p>
                                        </div>
                                        <div className='border-b-[3px] border-[#3B28CC] w-full  h-[60px] text-left pl-[24px] pt-[15px] font-[700] text-[30px] flex'>
                                            <p className='text-[16px] font-[700]'>1,000+ VIV</p>
                                            <p className='pl-[250px] text-[16px] font-[700] text-[#7AFDD6]'>14.35%</p>
                                        </div>
                                        <div className='border-b-[3px] border-[#3B28CC] w-full  h-[60px] text-left pl-[24px] pt-[15px] font-[700] text-[30px] flex'>
                                            <p className='text-[16px] font-[700]'>3,000+ VIV</p>
                                            <p className='pl-[240px] text-[16px] font-[700] text-[#7AFDD6]'>28.660%</p>
                                        </div>
                                        <p className='pl-[20px] text-[16px] font-[700] text-white mt-[31px]'>
                                            Connect wallet to see your POLS tier
                                        </p>
                                        <Btn className='mt-[5px] text-[14px]'  text={'Buy VIV & Level up'}></Btn>
                                        <p className='pl-[20px] text-[12px] font-[700] text-white mt-[4px]'>
                                            Probabilities are averages calculated over the most<br />
                                            recent IDOs. Chances are not guaranteed.
                                        </p>
                                    </div>
                                </div>

                                <div className='w-[100%] h-[500px] bg-gradient-to-br from-[#3E3394] to-[#262436] mt-[49px] pt-[2px] pl-[2px] rounded-[20px]'>
                                    <div className='w-[99.9%] h-[494px]  rounded-[20px] pt-[15px] bg-gradient-to-br from-[#282452] to-[#323046]'>
                                        <img src='./img/chart.png' className=' mt-[79px] ml-[32px]' />
                                    </div>
                                </div>
                            </div>
                            <div className='w-[95%]   h-auto  '>
                                <div className='w-[100%]  rounded-[30px]  h-[445px] ml-[30px] border-[#9E9DA7] bg-[#100E21] border-[2px]'>
                                    <div className='w-full flex  h-[73px] rounded-tr-[30px] text-[20px] font-[700]'>
                                        <div className='w-[50%] flex  h-[73px] rounded-tr-[20px] pl-[107px] text-white pt-[19px]'>
                                            Deposit
                                        </div>
                                        <div className='w-[50%] flex bg-[#9E9DA7] h-[73px] rounded-tr-[20px] pl-[120px] text-[#3B28CC] pt-[17px]'>
                                            Withdraw
                                        </div>
                                    </div>
                                    <p className='text-left ml-[13px] mt-[30px] text-[16px] font-[500]'>Stake VIV to participate in allowlists for upcoming IDOs.
                                        <span className='text-[#7AFDD6] ml-[23px]'>  Learn more</span>  </p>
                                    <div className='h-[26px] ml-[13px] text-left flex text-[14px] font-[400] mt-[30px]'>
                                        <p>Stake Amount</p>
                                        <p className='ml-[60%]'>Stake Amount</p>
                                    </div>
                                    <div className='w-[95%] h-[134px] ml-[13px] text-left  text-[16px] font-[400] mt-[10px] bg-[#211F41] rounded-[10px]'>
                                        <p className='pt-[40px] pl-[13px] text-[16px] font-[700] flex'>0:00  ......................................................................................
                                            <div className='w-[80px] h-[44px] bg-[#7AFDD6] mt-[-19px] ml-[4px] rounded-[7px] pl-[20px] pt-[9px] text-black'>Max</div>
                                        </p>
                                        <p className='ml-[13px] text-[16px] font-[700] mt-[10px]'>VIV  .......................................................................................  $000</p>
                                    </div>
                                    <button className='w-[80%] h-[50px] text-[17px] font-[500] mt-[20px] border-[2px] border-[#3B28CC] rounded-[100px] p-[0px]  '>
                                        Unsupported Network
                                    </button>
                                </div>
                                 <div className='w-[99%] h-[400px] bg-gradient-to-br from-[#3E3394] to-[#262436] mt-[50px] pt-[2px] pl-[2px] rounded-[20px] ml-[32px]'>
                                    <div className='w-[100%] h-[396px]  rounded-[20px] bg-gradient-to-br from-[#282452] to-[#323046]'>
                                        <div className='border-b-[3px] border-[#3B28CC] w-full  h-[129px] text-left pl-[14px] pt-[24px] font-[700] text-[20px]'>
                                            Your app participate
                                            <div className='flex'>
                                                <p className='font-[700] text-[16px] mt-[10px]'>Project Name</p>
                                                <p className='font-[700] text-[16px] mt-[10px] ml-[20%]'>Sale Date</p>
                                                <p className='font-[700] text-[16px] mt-[10px] ml-[20%]'>Status</p>
                                            </div>
                                            <p className='font-[700] text-[20px] ml-[29px] mt-[48px] '>
                                                Start by applying to an upcoming project
                                            </p>
                                            <p className='font-[500] text-[16px] ml-[0px] mt-[20px] text-center'>
                                                To get allowlisted, you first need to apply to a Project.<br />
                                                Learn how to apply here.
                                            </p>
                                            <button className={'w-[93%] ml-[8px] h-[50px] rounded-full mt-[39px] text-[18px]  font-[500] bg-gradient-to-r  from-[#3B28CC] to-[#E83151] bg-no-repeat '} >

                                                Go to Projects
                                            </button>

                                        </div>
                                    </div>
                                </div>
                               <div className='w-[99%] h-[496px] bg-gradient-to-br from-[#3E3394] to-[#262436] mt-[50px] pt-[2px] pl-[2px] rounded-[20px] ml-[32px]'>
                                    <div className='w-[100%] h-[494px]  rounded-[20px] bg-gradient-to-br from-[#282452] to-[#323046]'>
                                        <div className='border-b-[3px] border-[#3B28CC] w-full  h-[90px] text-left pl-[12px] pt-[17px] font-[700] text-[20px]'>
                                            Points previe

                                        </div>
                                        <div className='border-b-[3px] border-[#3B28CC] w-full  h-[83px] text-left pl-[8px] pt-[17px] font-[500] text-[16px]'>
                                            numbers  ........................................................................ Point



                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div className='bg-[#E5E1FF] dark:bg-gradient-to-r from-[#302f2f] to-[#221f41] w-[93%] mx-auto ml-[44px] h-[100px] border-[3px] border-[#3B28CC] mt-[46px] rounded-[20px]  font-bold text-gray-500'>
                            <p className='ml-[32px] mt-[20px] text-[16px] font-[700] text-white'>
                                Total Investment Amount  ................................................  $15000
                            </p>
                        </div>
                        <div className='bg-[#E5E1FF] bg-gradient-to-br from-[#4B4292] to-[#4E468E]   w-[93%] mx-auto ml-[44px] h-[320px] mt-[36px] rounded-[20px]  pt-[2px]'>
                            <div className='bg-[#E5E1FF] bg-gradient-to-br from-[#3B3957] to-[#4D458C]   w-[99.8%] mx-auto  h-[318px]  rounded-[20px]  font-bold text-gray-500'>
                                <div className='w-full h-[90px] border-b-[2px] border-[#3B28CC]'>
                                    <p className='text-[20px] font-[700] text-white pl-[33px] pt-[27px]'>List of projects</p>
                                </div>
                            </div>
                        </div>

                    </div>

                    <Modal ch={open}></Modal>
                </div>
                <div className='w-full h-[2px] bg-[#7AFDD6] mt-[50px]'>

                </div>

                <Footer></Footer>
            </div>
        </div>

    )
}
export default Dashbord;