import type { NextPage } from 'next'
import footer from '../common/footer'
import Head from "next/head";
import Image from 'next/image'
import logo from '../public/img/logo.png'
import Footer from '../common/footer'
import Link from 'next/link';
import Menu from '../common/menu';
import React, { useState } from 'react';
import Modal from '../commponent/Modal';
import Btn from '../common/btn';

const Lottery: NextPage = () => {
    const [open, setOpen] = useState(1);

    const handleClick = () => {
        if (open == 1) {
            setOpen(0)
        } else {
            setOpen(1);
        }
    }
    const setfun = () => {
      
    }

    return (
        <div className='bg-amir dark:bg-[#16142E]   h-auto lg:w-full xl:w-[1512px] m-0 m-auto  '>
            <Head>
                <title>   Lottery </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className=' w-[1512px] lg:flex h-auto m-0 m-auto col-span-2 bg-[#D3D3D3] dark:bg-[#16142E] '>
                <div className='w-[247px] hidden lg:block   h-auto '>
                    <div className='h-[126px] w-[247px]   lg:block pl-[33px]  dark:text-[#7AFDD6] dark:bg-[#211F41] lg:pt-[40px] font-[900] text-[35px] border-b-[1px] bg-[#F0EEFF] border-r-[1px] border-[#e4e2eff5] '>
                        Vivastarter
                    </div>
                    <Menu />


                </div>
                <div className='w-full h-auto '>
                    <div className='h-[126px] text-right w-full flex  dark:bg-[#211F41] bg-[#F0EEFF] border-b-[1px] border-gray-600 '>
                        <div className='w-[60%] flex'>
                            <div className='w-[201px] h-[126px] border-r-[0.5px] text-[#7AFDD6] border-[#9b9999] text-left flex pt-[53px] pl-[20px] text-[20px]' >
                                connected     <img src='./img/leak.svg' className='w-[48px] h-[48px] mt-[-11px] ml-[10px]' />
                            </div>
                            <div className='w-[310px] h-[126px] border-r-[0.5px] text-[#FFE346] border-[#9b9999] text-left flex pt-[53px] pl-[20px] text-[20px]' >
                                Click here to buy launchpool
                            </div>
                            <div className='w-[229px] h-[126px] border-r-[0.5px] text-[#FFE346] border-[#9b9999] text-left  pt-[40px] pl-[20px] ' >
                                <p className='text-[16px] text-white font-[500]'>Current Network</p>
                                <p className='text-[#FFE346] text-[20px] font-[700]'>Binace Smart Chain</p>

                            </div>
                        </div>

                        <Btn text={'Create Account '} handleClick={handleClick} ></Btn>
                        <Btn text={'Sign in '} handleClick={handleClick} ></Btn>


                    </div>

                    <div className=' w-[1204px] m-0 m-auto ml-[30px] h-[65px] mt-[72px] rounded-[20px]  font-bold flex text-gray-500'>
                        <div className='w-[556px] h-[65px] text-[50px] text-white'>Welcome to the lottery</div>
                        <button className='w-[219px] h-[76px] bg-[#FFFFFF] ml-[426px] mt-[0px]  text-left flex text-[#3B28CC] text-[20px] font-[700] pl-[33px] rounded-[20px]'>
                            <p className='pt-[23px]'> Round 3</p>
                            <img src='./img/icon/so.png' className='w-[44px] h-[50.55px]  ml-[33px] cursor-pointer  mt-[13px]' />

                        </button>
                    </div>

                    <div className=' flex  gap-[20px]  w-[1205px] m-0 m-auto ml-[30px] h-[306px] mt-[56px] rounded-[23px]  font-bold text-gray-500'>
                        <div className='w-[272px] rounded-[20px] border-[2px] border-[#FFC84D]  h-[305px] '>
                            <div className='h-[225px] w-full rounded-tr-[20px] rounded-tl-[20px] bg-[#211F41] text-[100px] font-[900] text-white pl-[66px] pt-[43px]'>
                                28
                            </div>
                            <p className='text-[30px] font-[700] text-white ml-[88px] mt-[10px]'> Days</p>
                        </div>
                        <p className='font-[700] text-[100px] mt-[60px] text-white'>:</p>
                        <div className='w-[272px] rounded-[20px] border-[2px] border-[#FFC84D]  h-[305px] '>
                            <div className='h-[225px] w-full rounded-tr-[20px] rounded-tl-[20px] bg-[#211F41] text-[100px] font-[900] text-white pl-[66px] pt-[43px]'>
                                10
                            </div>
                            <p className='text-[30px] font-[700] text-white ml-[88px] mt-[10px]'> Hours</p>
                        </div>
                        <p className='font-[700] text-[100px] mt-[60px] text-white'>:</p>
                        <div className='w-[272px] rounded-[20px] border-[2px] border-[#FFC84D]  h-[305px] '>
                            <div className='h-[225px] w-full rounded-tr-[20px] rounded-tl-[20px] bg-[#211F41] text-[100px] font-[900] text-white pl-[66px] pt-[43px]'>
                                00
                            </div>
                            <p className='text-[30px] font-[700] text-white ml-[88px] mt-[10px]'> Mins</p>
                        </div>
                        <p className='font-[700] text-[100px] mt-[60px] text-white'>:</p>
                        <div className='w-[272px] rounded-[20px] border-[2px] border-[#FFC84D]  h-[305px] '>
                            <div className='h-[225px] w-full rounded-tr-[20px] rounded-tl-[20px] bg-[#211F41] text-[100px] font-[900] text-white pl-[66px] pt-[43px]'>
                                44
                            </div>
                            <p className='text-[30px] font-[700] text-white ml-[88px] mt-[10px]'> Secs</p>
                        </div>
                    </div>
                    <div className='bg-[#E5E1FF] border-[2px] border-[#FFC84D]  dark:bg-[#211F41]  flex w-[1205px] m-0 m-auto ml-[30px] h-[209px] mt-[67px]  p-[10px] font-bold text-gray-500 rounded-[23px]'>
                        <div className='w-[252px] h-[141px] mt-[5px] ml-[45px] '>
                            <p className='font-[700] text-[50px] text-white'>Total price</p>
                            <p className='font-[700] text-[50px]  text-[#FFE346]'>50.000$ </p>
                        </div>
                        <img src='./img/icon/ban.png' className='w-[140px] h-[114.87px]  ml-[710px] cursor-pointer  mt-[30px]' />

                    </div>
                    <div className='text-white  w-[1205px] m-0 m-auto ml-[30px] h-[65px] mt-[61px]  text-[50px] font-[700]  '>
                        Previous round winners
                    </div>
                    <div className='flex gap-[150px]  w-[1205px] m-0 m-auto ml-[30px] h-[355px] mt-[66px]   font-bold text-gray-500 '>
                        <div className='w-[300px] h-[355px] '>
                            <div className='w-[135px] h-[135px]  ml-[82px] rounded-full absolute'>
                                <img src='./img/icon/women.png' className='' />

                            </div>
                            <div className='pt-[55px]'>
                                <div className='w-[300x] h-[300px]  border-[2px] rounded-[20px] border-white  bg-[#211F41] mt-[0px]'>
                                    <div className='w-[272px] h-[162px]  mt-[122px] ml-[13px] bg-taj'>
                                        <p className='ml-[61.83px] pt-[80px] text-[#E83151] font-[700] text-[30px]'>50.000.000$</p>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div className='w-[300px] h-[355px] '>
                            <div className='w-[135px] h-[135px]  ml-[82px] rounded-full absolute'>
                                <img src='./img/icon/women.png' className='' />

                            </div>
                            <div className='pt-[55px]'>
                                <div className='w-[300x] h-[300px]  border-[2px] rounded-[20px] border-white  bg-[#211F41] mt-[0px]'>
                                    <div className='w-[272px] h-[162px]  mt-[122px] ml-[13px] bg-taj'>
                                        <p className='ml-[61.83px] pt-[80px] text-[#E83151] font-[700] text-[30px]'>50.000.000$</p>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div className='w-[300px] h-[355px] '>
                            <div className='w-[135px] h-[135px]  ml-[82px] rounded-full absolute'>
                                <img src='./img/icon/women.png' className='' />

                            </div>
                            <div className='pt-[55px]'>
                                <div className='w-[300x] h-[300px]  border-[2px] rounded-[20px] border-white  bg-[#211F41] mt-[0px]'>
                                    <div className='w-[272px] h-[162px]  mt-[122px] ml-[13px] bg-taj'>
                                        <p className='ml-[61.83px] pt-[80px] text-[#E83151] font-[700] text-[30px]'>50.000.000$</p>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div className=' w-[1205px] m-0 m-auto leading-[50px]  h-[255px] mt-[40px] text-[20px]  font-[500] text-white '>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt utgray-500 labore et dolore magna In <br />
                        erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus. Mattis pellentesque id  nibh tortor id aliquet <br />
                        lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed u . nibh tortor id aliquet lectus <br />
                        proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed  aliqua. Egestas purus viverra accumsan<br />
                        in nisl nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque.

                    </div>
                    <div className='  w-[1205px] m-0 m-auto ml-[30px] h-[50px] mt-[59px]   font-bold text-gray-500 '>
                        <button className={'w-[459px]  h-[50px] text-white rounded-full  text-[18px]  font-[500] bg-gradient-to-r  from-[#3B28CC] to-[#E83151] bg-no-repeat '} >
                            Go to Lottery
                        </button>
                    </div>


                </div>
                <Modal ch={open}></Modal>

            </div>
            <div className='w-full h-[3px] bg-blue-300 mt-10'>

            </div>

            <Footer></Footer>
        </div>
    )
}
export default Lottery;