import type { NextPage } from 'next'
import footer from '../common/footer'
import Head from "next/head";
import Image from 'next/image'
import logo from '../public/img/logo.png'
import Footer from '../common/footer'
import Link from 'next/link';
import Menu from '../common/menu';
import Modal from '../commponent/Modal';
import Btn from '../common/btn';
import React, { useState, useEffect } from 'react';
import UserService from '../Infrastructure/Services/user.service';
interface user {
    email: string
    dedicateid: string
}
const Reffrall: NextPage = () => {
    const [open, setOpen] = useState(1);
    const [userdetail, setdetail] = useState<user>();
    const [listuser, setuser] = useState<user[]>();
    const handleClick = () => {
        if (open == 1) {
            setOpen(0)
        } else {
            setOpen(1);
        }
    }
    useEffect(() => {
        UserService.getdetail().then(p => {
            setdetail(p.data)
            UserService.listrefferalluser(p.data['dedicateid']).then(o => {
                setuser(o.data)
            })
        })
    }, [])
    return (
        <div className='bg-amir dark:bg-[#16142E] '>

            <div className='container h-auto mx-auto'>
                <Head>
                    <title>  refferal  </title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className=' w-full lg:flex h-auto col-span-2 bg-[#D3D3D3] dark:bg-[#16142E]'>
                    <div className='w-[15%] hidden lg:block   h-auto '>
                        <div className=' xl:h-[80px] w-[100%]   lg:block  xl:pl-[16px]  dark:text-[#7AFDD6] dark:bg-[#211F41] xl:pt-[16px]  font-[900]  xl:text-[16px] border-b-[1px] bg-[#F0EEFF] border-r-[1px] border-[#e4e2eff5] '>
                            Vivastarter
                        </div>
                        <Menu />


                    </div>
                    <div className='w-full h-auto '>
                        <div className=' xl:h-[80px]  text-right w-full flex  dark:bg-[#211F41] bg-[#F0EEFF] border-b-[1px] border-gray-600 '>
                            <div className='w-[68%] flex'>
                                <div className='w-[201px]  xl:h-[80px] border-r-[0.5px] border-[#9b9999] text-left flex  xl:pt-[26px] pl-[16px]  xl:text-[16px]' >
                                    connected     <img src='../img/leak.svg' className=' xl:w-[38px]  xl:h-[38px] mt-[-10px] ml-[10px]' />
                                </div>
                                <div className='w-[201px]  xl:h-[80px] border-r-[0.5px] border-[#9b9999] text-left flex  xl:pt-[15px] pl-[16px]  xl:text-[16px]' >
                                    Click here to buy launchpool
                                </div>

                                <div className='w-[229px] h-[80px] border-r-[0.5px] text-[#FFE346] border-[#9b9999] text-left  pt-[15px] pl-[20px] ' >
                                    <p className='text-[14px] text-white font-[500]'>Current Network</p>
                                    <p className='text-[#FFE346] text-[16px] font-[700]'>Binace Smart Chain</p>

                                </div>
                            </div>



                        </div>

                        <div className='w-[93%] mx-auto mt-[31px] h-[50px]  '>
                            <input placeholder='Link: www...////.com' className='w-[82%] text-black border-none dark:bg-white rounded-bl-[20px] rounded-tl-[20px] text-left pl-[10px] h-[50px] focus:border-[2px] focus:border-red-500 ' value={process.env.REACT_APP_Bse_Url+'/listprojects?pid=' + userdetail?.dedicateid} />
                            <button className='w-[160px] rounded-tr-[20px] rounded-br-[20px]  h-[52px] font-bold  text-white dark:bg-gradient-to-r from-blue-900 to-[#E83151]'>
                                Copy Link
                            </button>
                        </div>
                        <div className='w-[92%]  mx-auto mt-[50px] pt-[2px] pl-[1px] h-auto rounded-[15px]  dark:bg-gradient-to-r from-blue-900 to-gray-700'>

                            <div className='grid grid-cols-5 w-[99.9%] ml-[2px] rounded-[15px]  text-center h-auto text-[15px] font-bold cursor-pointer dark:bg-gradient-to-r from-[#2C275E] to-[#23213D]'>
                                <div className='border-[1px] rounded-tl-[15px] border-r-0 border-b-0 h-[85px]  border-blue-600 border-t-0 border-l-0 pl-[17px] pt-[26px] text-[17px] font-[700]'>Email</div>
                                 <div className='border-[1px]  h-[85px] border-r-0 border-b-0  p-3  border-blue-600 border-t-0 pl-[17px] pt-[26px] text-[17px] font-[700]'>Level</div>
                                <div className='border-[1px]  h-[85px] border-r-0 border-b-0  p-3  border-blue-600 border-t-0 pl-[17px] pt-[26px] text-[17px] font-[700]'>benefit</div>
                                <div className='border-[1px]  h-[85px] border-r-0 border-b-0 p-3  border-blue-600 border-t-0 pl-[17px] pt-[26px] text-[17px] font-[700] col-span-2'>Investment amount</div>
                                {
                                    listuser?.map((input, index) => {
                                        return (
                                            <>
                                                <div className='border-[1px] border-r-0 border-b-0  h-[85px] p-3  border-blue-600 border-l-0 pl-[11px] pt-[20px] text-[15px] font-[500]'>{input.email}</div>
                                                <div className='border-[1px] border-r-0 border-b-0 h-[85px]  p-3  border-blue-600 pt-[29px] text-[16px]'>1</div>
                                                <div className='border-[1px] border-r-0 border-b-0  h-[85px]  p-3  border-blue-600 pt-[28px] text-[16px]'>0$</div>
                                                <div className='border-[1px] border-r-0 border-b-0 h-[85px]  p-3  border-blue-600 col-span-2 pt-[20px] text-[16px]'>0$ </div>
                                            </>
                                        )
                                    })
                                }




                            </div>

                        </div>
                        <div className='w-[93%] grid grid-cols-2 gap-[24px]  pt-2 mx-auto  h-auto  '>

                            <div className=' w-[100%] h-[254px] bg-gradient-to-r  from-blue-900 to-gray-800 rounded-[12px] pt-1 mt-[50px] mx-auto '>
                                <div className='bg-[#E5E1FF] dark:bg-[#241E4B] w-[99.9%] h-[252px]  mx-auto   rounded-[12px] p-[10px] font-bold text-white'>
                                    Description
                                </div>
                            </div>
                            <div className=' w-[100%] h-[255px] bg-gradient-to-r  from-blue-900 to-gray-800 rounded-[12px] pt-1 mt-[50px] mx-auto '>
                                <div className='bg-[#E5E1FF] dark:bg-[#241E4B] w-[99%] h-[247px]  mx-auto   rounded-[12px]  font-bold text-white'>
                                    <div className='h-[82px] rounded-tl-[12px] rounded-tr-[12px] bg-[#3A3661] text-center text-[20px] font-[700] pt-[21px] '>
                                        profitability
                                    </div>
                                    <div className='grid grid-cols-3 h-[85px] text-center  font-bold cursor-pointer'>
                                        <div className='border-[1px] text-[20px]  h-[85px] pt-[20px] pl-[50px]  border-blue-600'>Number</div>
                                        <div className='border-[1px]  h-[85px] pt-[20px] pl-[50px]  border-blue-600'>Percentage</div>
                                        <div className='border-[1px]  h-[85px] pt-[20px] pl-[50px]  border-blue-600'>Description</div>

                                        <div className='border-[1px] border-b-0  border-l-0 text-[20px]  h-[85px] pt-[20px] pl-[50px]  border-blue-600'></div>
                                        <div className='border-[1px] border-b-0  h-[85px] pt-[20px] pl-[50px]  border-blue-600'>Percentage</div>
                                        <div className='border-[1px] border-b-0  border-r-0 h-[85px] pt-[20px] pl-[50px]  border-blue-600'></div>
                                    </div>

                                </div>
                            </div>
                            {/* <div className='bg-[#352F68] h-[255px] w-[589px] mt-[47px] rounded-[25px] '>
                            <div className='h-[82px] rounded-tl-[25px] rounded-tr-[25px] bg-[#3A3661] text-center font-bold pt-4'>
                                profitability
                            </div>
                            <div className='grid grid-cols-3 text-center text-[25px] font-bold cursor-pointer'>


                                <div className='border-[1px]  h-12 p-3  border-blue-600'>Number</div>
                                <div className='border-[1px]  h-12 p-3  border-blue-600'>Percentage</div>
                                <div className='border-[1px]  h-12 p-3  border-blue-600'>Description</div>



                            </div>
                        </div> */}
                        </div>

                    </div>

                </div>
                <div className='w-full h-[2px] bg-[#7AFDD6] mt-[50px]'>

                </div>
                <Footer></Footer>
            </div>
        </div>

    );
}
export default Reffrall;